### ISSUE TITLE
Support for other platforms?

### ISSUE THREAD

**Issue by ForceGT** [Path-Check/universal-verifier-sdk#2]
Hello, first of all congratulations on the sdk, it looks solid. I have limited experience with JavaScript and I would like to know if there is an SDK available for Java and Swift as I would like to use it for my apps

**Comment by vitorpamplona** [comment]
Hi Gaurav, 

We don't have much experience with Java and Swift, but if you build something similar and it can be open source, we would love to support your development somehow. We just don't see much use of Java and Swift these days among our users. 

Best,
